#!/bin/bash
#
# Sisyphus Device Reset Script
#
# This script was generated by an LLM, after which it got reviewed, i cannot bother
# myself with writing this thing.
#
# This script first searches for a specific Sisyphus's VID/PID, sends a reset command and exits
# gracefully if it's found.
# It also searches for Eternity's VID/PID and when if found, exits gracefuly so the device can
# be recovered from a broken state.

# --- Configuration ---
set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error when substituting.
set -o pipefail # Causes a pipeline to return the exit status of the last command that exited with a non-zero status

# --- Device Identification ---
# Sisyphus's VID/PID
PRODUCT_ID="cafe/6942"
# Eternity's VID/PID
ETERNITY_PID="cafe/6940"
# The pattern for where to find device information on modern Linux systems.
DEVICE_PATTERN="/sys/class/tty/*/device/uevent"

# --- Script Logic ---

echo "Searching for devices..."

# 1. Check for Eternity first.
# If a device with ETERNITY_PID (cafe/6940) is found, exit without error.
if grep -rq "PRODUCT=${ETERNITY_PID}" ${DEVICE_PATTERN}; then
    echo "Detected Eternity (${ETERNITY_PID}). Exiting without reset."
    exit 0
fi

# 2. If Eternity wasn't found, search for the primary Sisyphus device.
# - `head -n 1` takes the first device found.
# - `|| true` allows grep to find nothing without the script exiting due to `set -e`.
DEVICE_FILE=$(grep -ril "PRODUCT=${PRODUCT_ID}" ${DEVICE_PATTERN} | head -n 1 || true)

# 3. Validate that the primary device was found.
if [[ -z "$DEVICE_FILE" ]]; then
    echo "Error: Sisyphus device (${PRODUCT_ID}) not found." >&2
    exit 1
fi

# 4. Extract the device path (e.g., /dev/ttyACM0).
DEV_PATH=$(sed 's|/sys/class/tty/\(.*\)/device/uevent|/dev/\1|' <<< "$DEVICE_FILE")

if [[ -z "$DEV_PATH" ]]; then
    echo "Error: Could not determine device path from '${DEVICE_FILE}'." >&2
    exit 1
fi

# 5. Verify that the path points to a character device.
if [ ! -c "$DEV_PATH" ]; then
    echo "Error: Path '${DEV_PATH}' is not a Sisyphus device." >&2
    exit 1
fi

echo "Found device: ${DEV_PATH}"
echo "Sending reset command..." >&2

# 6. Send the reset sequence.
if ! printf "reset\x04" > "${DEV_PATH}"; then
    echo "Error: Failed to write reset command to ${DEV_PATH}. Check permissions." >&2
    exit 1
fi

sleep 1
echo "Reset command sent successfully."
exit 0
